/* DOM/GL adapters exercise gameplay UI commands; they do not provide browser visual QA. */
import test from 'node:test';import assert from 'node:assert/strict';import {mockGL} from './helpers/gl.mjs';import {mock2D} from './helpers/canvas.mjs';
const nodes=new Map(),listeners=new Map(),data=new Map();let frameCallback;
class Node {constructor(id){this.id=id;this._html='';this._class='';this.classes=new Set();this.dataset={};this.style={};this.hidden=true;this.tagName='DIV';this.classList={add:x=>this.classes.add(x),remove:x=>this.classes.delete(x),contains:x=>this.classes.has(x),toggle:(x,y)=>y?this.classes.add(x):this.classes.delete(x)};}set className(v){this._class=v;this.classes=new Set(v.split(' '));}get className(){return this._class;}set innerHTML(v){this._html=v;for(const match of v.matchAll(/id="([^"]+)"/g))if(!nodes.has('#'+match[1]))nodes.set('#'+match[1],new Node(match[1]));}get innerHTML(){return this._html;}addEventListener(type,fn){listeners.set(this.id+':'+type,fn);}append(){}setAttribute(){}focus(){}setPointerCapture(){}querySelector(s){return new Node(s);}querySelectorAll(){return [];}click(){}remove(){}}
for(const id of ['space','hud','overlay','notice','fatal','world-labels'])nodes.set('#'+id,new Node(id));
const {gl}=mockGL(),canvas=nodes.get('#space');const {ctx}=mock2D();const attachCanvas=node=>Object.assign(node,{clientWidth:390,clientHeight:844,width:0,height:0,getContext:mode=>mode==='2d'?ctx:process.env.APOGEE_SOFTWARE_TEST?null:gl,cloneNode:()=>attachCanvas(new Node('space')),replaceWith:fresh=>nodes.set('#space',fresh)});attachCanvas(canvas);
globalThis.document={querySelector:s=>nodes.get(s)||null,createElement:()=>new Node('created'),addEventListener:(type,fn)=>listeners.set('document:'+type,fn),hidden:false};
globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};globalThis.window={addEventListener:(type,fn)=>listeners.set('window:'+type,fn)};
Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.innerWidth=1200;globalThis.innerHeight=700;globalThis.requestAnimationFrame=fn=>{frameCallback=fn;};globalThis.setTimeout=()=>0;globalThis.clearTimeout=()=>{};
await import('../dist/frontier.js');
const click=(action,id)=>listeners.get('document:click')({target:{closest(){return {dataset:{action,id},disabled:false};}}});
let clock=0;const flight=()=>{for(let i=0;i<220;i++){clock+=100;frameCallback(clock);}};
const course=id=>{click('course',id);click('cruise');flight();};
test('first-person game shows an actionable title screen and starts the expedition',()=>{assert.match(nodes.get('#overlay').innerHTML,/Far from home/);assert.match(nodes.get('#overlay').innerHTML,/Enter the frontier/);click('start');assert.equal(nodes.get('#overlay').innerHTML,'');assert.equal(nodes.get('#hud').style.display,'');});
test('navigation, cruise and interaction collect resources and open the habitat fabricator',()=>{click('map');assert.match(nodes.get('#overlay').innerHTML,/The frontier is yours to chart/);course('wreck1');click('interact');assert.match(nodes.get('#notice').textContent,/recovered 6 cargo units/);course('home');click('interact');assert.match(nodes.get('#overlay').innerHTML,/FABRICATOR/);assert.match(nodes.get('#overlay').innerHTML,/Titanium alloy/);assert.equal(JSON.parse(data.get('apogee-frontier-v2')).storage.alloy,4);});
test('resource trip and crafting finish the first survival objective through UI actions',()=>{course('ice1');click('interact');course('home');click('interact');click('craft','life');const s=JSON.parse(data.get('apogee-frontier-v2'));assert.ok(s.modules.includes('life'));assert.equal(s.storage.ice,6);assert.equal(s.credits,117);assert.match(nodes.get('#objective-title').textContent,/Follow the first whisper/);assert.match(nodes.get('#overlay').innerHTML,/INSTALLED/);});
test('graphics context loss retains progress and continues in software mode',()=>{const before=JSON.parse(data.get('apogee-frontier-v2'));click('close');listeners.get('space:webglcontextlost')({preventDefault(){}});assert.match(nodes.get('#notice').textContent,/compatibility graphics/);assert.deepEqual(JSON.parse(data.get('apogee-frontier-v2')).modules,before.modules);click('close');course('wreck2');click('interact');assert.match(nodes.get('#notice').textContent,/recovered/);});
test('field log, handbook and reload preserve a resumable expedition',async()=>{click('journal');assert.match(nodes.get('#overlay').innerHTML,/Export expedition save/);click('help');assert.match(nodes.get('#overlay').innerHTML,/300 kg design limit/);await import('../dist/frontier.js?restore=1');assert.match(nodes.get('#overlay').innerHTML,/Resume expedition/);assert.equal(JSON.parse(data.get('apogee-frontier-v2')).modules[0],'life');});
