import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {createSpaceRenderer,CanvasSpaceRenderer} from '../dist/canvas-renderer.js';
import {create,SITES,orient} from '../dist/survival.js';import {mockGL} from './helpers/gl.mjs';import {mock2D} from './helpers/canvas.mjs';
function surface(gl=null){const {ctx,stats}=mock2D();let replaced=false;const fresh={clientWidth:390,clientHeight:844,width:0,height:0,getContext:type=>type==='2d'?ctx:null};const canvas={...fresh,getContext:type=>type==='webgl'?gl:null,cloneNode:()=>fresh,replaceWith(node){assert.equal(node,fresh);replaced=true;}};return {canvas,fresh,stats,replaced:()=>replaced};}
test('unsupported WebGL replaces the canvas and starts software flight',()=>{const s=surface(),r=createSpaceRenderer(s.canvas);assert.equal(r.mode,'canvas');assert.ok(s.replaced());r.render(create());assert.ok(s.stats().draws>100);assert.equal(s.fresh.width,390);});
test('shader link rejection recovers through a fresh software canvas',()=>{const {gl}=mockGL();gl.getProgramParameter=()=>false;const s=surface(gl),r=createSpaceRenderer(s.canvas);assert.ok(r instanceof CanvasSpaceRenderer);assert.ok(s.replaced());r.render(create());});
test('explicit compatibility mode avoids acquiring WebGL',()=>{const s=surface();s.canvas.getContext=()=>{throw Error('Must not request WebGL');};assert.equal(createSpaceRenderer(s.canvas,{software:true}).mode,'canvas');});
test('software projection remains finite in portrait and landscape at every destination',()=>{const s=surface(),r=createSpaceRenderer(s.canvas),state=create();for(const [w,h] of [[390,844],[844,390]]){s.fresh.clientWidth=w;s.fresh.clientHeight=h;for(const site of SITES){state.pos=site.pos.map((v,i)=>v+(i===2?site.radius+90:0));orient(state,site.pos);r.render(state,100);const p=r.marker(site.pos);assert.ok(p);assert.ok(Math.abs(p.x-w/2)<.1);assert.ok(Math.abs(p.y-h/2)<.1);}}});
test('phone without WebGL completes UI flight, salvage, docking, crafting and reload',()=>{const env={...process.env,APOGEE_SOFTWARE_TEST:'1'};delete env.NODE_TEST_CONTEXT;const output=execFileSync(process.execPath,['--test','tests/frontier-ui.test.mjs'],{cwd:new URL('..',import.meta.url),env,encoding:'utf8'});assert.match(output,/pass 5/);assert.match(output,/fail 0/);});
